import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/providers";
import interFont from "@/assets/fonts/inter";
import chakraPetch from "@/assets/fonts/chakra-petch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chakraPetch.className}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
